default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: short_urls_development
test:
  <<: *default
  database: short_urls_test
production:
  <<: *default
  database: short_urls_production
  username: 
  password: 